Conda + docker support in setup script

diff --git a/bin/zdb b/bin/zdb
--- a/bin/zdb
+++ b/bin/zdb
@@ -82,11 +82,24 @@ elif [[ "$1" == "setup" ]]; then
 	dir="$(pwd)/zdb_ref"
 	db_setup_args=""
 	singularity_dir="$(pwd)/singularity"
+	singularity=true
+	docker=false
+	conda=false
 
 	for i in "$@"; do
 		case $i in 
 			--cog)
 				db_setup_args="${db_setup_args} --cog"
+				shift
+				;;
+			--conda)
+				conda=true
+				singularity=false
+				shift
+				;;
+			--docker)
+				docker=true
+				singularity=false
 				shift
 				;;
 			--ko)
@@ -111,19 +124,15 @@ elif [[ "$1" == "setup" ]]; then
 				;;
 			--help)
 				echo "Downloads and sets up the reference database used by the analysis pipeline"
-				echo ""
 				echo "The following options can be used"
-				echo ""
 				echo " --cog: downloads the CDD profiles used for COG annotations "
-				echo ""
 				echo " --ko: downloads and setups the hmm profiles of the ko database"
-				echo ""
 				echo " --pfam: downloads and setups up the hmm profiles of the PFAM protein domains"
-				echo ""
 				echo " --swissprot: downloads and indexes the swissprot database "
-				echo ""
 				echo " --dir: directory where to store the reference databases (defaults zdb_ref in the current directory) "
-				echo ""
+				echo "Environments (by default, singularity containers are used):"
+				echo "--conda: uses conda environment to prepare the databases"
+				echo "--docker: uses docker containers to prepare the databases"
 				echo " --singularity_dir: the directory where the singularity images are downloaded (default singularity in current directory)"
 				exit 0
 				;;
@@ -132,8 +141,18 @@ elif [[ "$1" == "setup" ]]; then
 				exit 1
 		esac
 	done
+	if [ "$docker" = true -a "$conda" = true ]; then
+		echo "Docker and conda cannot be set at the same time"
+		exit 1
+	elif [ "$docker" = true ]; then
+		env="--docker=true --conda=false --singularity=false"
+	elif [ "$conda" = true ]; then
+		env="--docker=false --conda=true --singularity=false"
+	else
+		env="--docker=false --conda=false --singularity=true"
+	fi
 
-	db_setup_args="${db_setup_args} --base_db=${dir} --singularity_dir=${singularity_dir}"
+	db_setup_args="${db_setup_args} --base_db=${dir} ${env} --singularity_dir=${singularity_dir}"
 	echo "Preparing the reference databases, this will take some time"
 	nextflow run $NEXTFLOW_DIR/db_setup.nf ${db_setup_args}
 	echo "Done. The reference databases were prepared in the ${dir} folder"
